spring:
  application:
    name: quiz-app
  datasource:
    url: jdbc:postgresql://localhost:5432/sims
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true